# Generated by Django 3.2.6 on 2021-10-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20210910_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='detail_images', verbose_name='Подробная картинка'),
        ),
    ]
