# Generated by Django 3.2.6 on 2021-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20211003_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platforms',
            field=models.CharField(blank=True, max_length=150, verbose_name='Платформы'),
        ),
    ]
