# Generated by Django 3.2.6 on 2021-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_product_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='store_images', verbose_name='Картинка в каталоге'),
        ),
    ]
